- hosts: all
  gather_facts: False
  become: true
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python2-minimal)

- hosts: wordpress

  roles:
    - server
    - php
    - mysql
    - wordpress
