---
# tasks file for server

- name: Update apt cache
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
  become: yes

- name: Install required software
  apt: 
    pkg: ['apache2', 'mysql-server', 'php7.2-mysql', 'php7.2', 'libapache2-mod-php7.2', 'python-mysqldb']
    state: present
  become: yes
